// DAX 40 – Zusammensetzung nach der Indexüberprüfung September 2026
// (letzte Änderung: 22.06.2026 Hochtief rein, Porsche SE raus).
// Dividende und Zahlmonat: letzte bekannte Ausschüttung, Richtwerte ohne Gewähr – bitte prüfen.
// month: 0 = Januar … 11 = Dezember
const DAX = [
  { name: 'adidas', sector: 'Konsum', dividend: 2.00, month: 4 },
  { name: 'Airbus', sector: 'Luftfahrt', dividend: 3.00, month: 3 },
  { name: 'Allianz', sector: 'Versicherung', dividend: 15.40, month: 4 },
  { name: 'BASF', sector: 'Chemie', dividend: 2.25, month: 4 },
  { name: 'Bayer', sector: 'Pharma', dividend: 0.11, month: 3 },
  { name: 'Beiersdorf', sector: 'Konsum', dividend: 1.00, month: 3 },
  { name: 'BMW', sector: 'Auto', dividend: 4.30, month: 4 },
  { name: 'Brenntag', sector: 'Chemie', dividend: 2.10, month: 5 },
  { name: 'Commerzbank', sector: 'Bank', dividend: 0.65, month: 4 },
  { name: 'Continental', sector: 'Auto', dividend: 2.50, month: 3 },
  { name: 'Daimler Truck', sector: 'Auto', dividend: 1.90, month: 3 },
  { name: 'Deutsche Bank', sector: 'Bank', dividend: 0.68, month: 4 },
  { name: 'Deutsche Börse', sector: 'Finanzen', dividend: 4.00, month: 4 },
  { name: 'Deutsche Telekom', sector: 'Telekom', dividend: 0.90, month: 3 },
  { name: 'DHL Group', sector: 'Logistik', dividend: 1.85, month: 4 },
  { name: 'E.ON', sector: 'Versorger', dividend: 0.55, month: 4 },
  { name: 'Fresenius', sector: 'Gesundheit', dividend: 1.00, month: 4 },
  { name: 'Fresenius Medical Care', sector: 'Gesundheit', dividend: 1.44, month: 4 },
  { name: 'GEA Group', sector: 'Maschinenbau', dividend: 1.00, month: 4 },
  { name: 'Hannover Rück', sector: 'Versicherung', dividend: 7.20, month: 4 },
  { name: 'Heidelberg Materials', sector: 'Bau', dividend: 3.30, month: 4 },
  { name: 'Henkel Vz.', sector: 'Konsum', dividend: 2.06, month: 4 },
  { name: 'Hochtief', sector: 'Bau', dividend: 5.00, month: 4 },
  { name: 'Infineon', sector: 'Halbleiter', dividend: 0.35, month: 1 },
  { name: 'Mercedes-Benz Group', sector: 'Auto', dividend: 4.30, month: 3 },
  { name: 'Merck KGaA', sector: 'Pharma', dividend: 2.35, month: 3 },
  { name: 'MTU Aero Engines', sector: 'Luftfahrt', dividend: 2.20, month: 4 },
  { name: 'Münchener Rück', sector: 'Versicherung', dividend: 20.00, month: 4 },
  { name: 'Qiagen', sector: 'Gesundheit', dividend: 0.23, month: 6 },
  { name: 'Rheinmetall', sector: 'Rüstung', dividend: 8.10, month: 4 },
  { name: 'RWE', sector: 'Versorger', dividend: 1.10, month: 4 },
  { name: 'SAP', sector: 'Software', dividend: 2.35, month: 4 },
  { name: 'Scout24', sector: 'Internet', dividend: 1.60, month: 5 },
  { name: 'Siemens', sector: 'Industrie', dividend: 5.20, month: 1 },
  { name: 'Siemens Energy', sector: 'Energietechnik', dividend: 0.70, month: 1 },
  { name: 'Siemens Healthineers', sector: 'Gesundheit', dividend: 0.95, month: 1 },
  { name: 'Symrise', sector: 'Chemie', dividend: 1.10, month: 4 },
  { name: 'Volkswagen Vz.', sector: 'Auto', dividend: 6.36, month: 5 },
  { name: 'Vonovia', sector: 'Immobilien', dividend: 1.22, month: 4 },
  { name: 'Zalando', sector: 'Handel', dividend: 0, month: null },
];
